version: '3.8'
services:
    kafkamanager: # https://github.com/yahoo/CMAK
        image: kafkamanager/kafka-manager
        container_name: kafkamanager
        hostname: kafkamanager
        ports:
            - 9000:9000
        environment:
            - "ZK_HOSTS=zookeeper1:22181,zookeeper2:32181,zookeeper3:42181"
        depends_on:
            - kafka
        networks:
            - broker-net
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
                max_attempts: 1

    visualizer:
        image: dockersamples/visualizer:stable
        hostname: visualizer
        ports:
        - "8888:8080"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - broker-net
        deploy:
            placement:
                constraints: [node.role == manager]    

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true