version: '3.8'
services:
    zookeeper1:
        image: zookeeper:3.4.9
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zookeeper1:2888:3888
        volumes:
            #- "/var/run/docker.sock:/var/run/docker.sock"
            - "zookeeper1-data:/var/lib/zookeeper1/data"
            - "zookeeper1-txn-logs:/var/lib/zookeeper1/log"
        container_name: zookeeper1
        ports:
            - "2181:2181"
        networks:
            - broker-net
        restart: always
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
                max_attempts: 1

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true
volumes:
    zookeeper1-data:
    zookeeper1-txn-logs: