version: '3.8'
services:
    mongo-express:
        image: mongo-express
        build: 
            context: .
            dockerfile: ./mongo/Dockerfile
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2022!
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2022!
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo-dronedb
        container_name: mongo-express
        ports:
            - "8081:8081"
        networks:
            - broker-net
        restart: always
        depends_on:
            - mongo-dronedb
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == worker]
            restart_policy:
                condition: on-failure
                max_attempts: 3

    drone-kafka-job:
        image: ricardosoareslacerda/drone-kafka-job:lastest
        environment:
            PATH_HOST_PRODUCER_DOCKER_INTERNAL: drone-kafka-producer:8082/api/v1/drones-monitor/
            RESOURCE_API_HOST_PRODUCER: drones/register/
        container_name: drone-kafka-job
        hostname: drone-kafka-job
        networks:
            - broker-net
        restart: always
        depends_on:
            - kafka
            - drone-kafka-producer
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == worker]
            restart_policy:
                condition: on-failure
                max_attempts: 3

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true