version: '3.8'
services:
    drone-kafka-job:
        image: ricardosoareslacerda/drone-kafka-job:lastest
        environment:
            PATH_HOST_PRODUCER_DOCKER_INTERNAL: drone-kafka-producer:8082/api/v1/drones-monitor/
            RESOURCE_API_HOST_PRODUCER: drones/register/
        container_name: drone-kafka-job
        hostname: drone-kafka-job
        networks:
            - broker-net
        restart: always
        depends_on:
            - kafka
            - drone-kafka-producer
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == worker]
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
                max_attempts: 1

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true