version: '3.8'
services:
    kafkamanager: # https://github.com/yahoo/CMAK
        image: kafkamanager/kafka-manager
        container_name: kafkamanager
        hostname: kafkamanager
        ports:
            - 9000:9000
        environment:
            - "ZK_HOSTS=zookeeper1:22181,zookeeper2:32181,zookeeper3:42181"
        depends_on:
            - kafka
        networks:
            - broker-net
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3

    kowl:
        image: quay.io/cloudhut/kowl:v1.4.0
        volumes:
            - ./kowl_config.yaml:/etc/kowl/config.yaml
        entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
        container_name: kowl
        ports:
            - "8080:8080"
        networks:
            - broker-net
        restart: always
        depends_on:
            - kafka
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3

    visualizer:
        image: dockersamples/visualizer:stable
        hostname: visualizer
        ports:
        - "8888:8080"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - broker-net
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true