version: '3.8'
services:
    zookeeper1:
        image: zookeeper:3.4.9
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 22181
            ZOO_SERVERS: server.1=0.0.0.0:22888:23888 server.2=zookeeper2:32888:33888 server.3=zookeeper3:42888:43888
        volumes:
            - "zookeeper1-data:/var/lib/zookeeper1/data"
            - "zookeeper1-txn-logs:/var/lib/zookeeper1/log"
        container_name: zookeeper1
        hostname: zookeeper1
        ports:
            - "22181:22181"
        networks:
            - broker-net
        restart: always
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3
    zookeeper2:
        image: zookeeper:3.4.9
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 32181
            ZOO_SERVERS: server.1=zookeeper1:22888:23888 server.2=0.0.0.0:32888:33888 server.3=zookeeper3:42888:43888
        volumes:
            - "zookeeper2-data:/var/lib/zookeeper2/data"
            - "zookeeper2-txn-logs:/var/lib/zookeeper2/log"
        container_name: zookeeper2
        hostname: zookeeper2
        ports:
            - "32181:32181"
        networks:
            - broker-net
        restart: always
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3
    zookeeper3:
        image: zookeeper:3.4.9
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 42181
            ZOO_SERVERS: server.1=zookeeper1:22888:23888 server.2=zookeeper2:32888:33888 server.3=0.0.0.0:42888:43888
        volumes:
            - "zookeeper3-data:/var/lib/zookeeper3/data"
            - "zookeeper3-txn-logs:/var/lib/zookeeper3/log"
        container_name: zookeeper3
        hostname: zookeeper3
        ports:
            - "42181:42181"
        networks:
            - broker-net
        restart: always
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true
volumes:
    zookeeper1-data:
    zookeeper1-txn-logs:
    zookeeper2-data:
    zookeeper2-txn-logs:
    zookeeper3-data:
    zookeeper3-txn-logs: