version: '3.8'
services:
    zookeeper:
        image: zookeeper:3.4.9
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        volumes:
            - "zookeeper-data:/var/lib/zookeeper/data"
            - "zookeeper-txn-logs:/var/lib/zookeeper/log"
        container_name: zookeeper1
        ports:
            - "2181:2181"
        networks:
            - broker-net
        restart: always
        deploy:
            replicas: 2
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
                max_attempts: 3

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true
volumes:
    zookeeper-data:
    zookeeper-txn-logs: