version: '3.8'
services:
    kafkamanager: # https://github.com/yahoo/CMAK
        image: kafkamanager/kafka-manager
        container_name: kafkamanager
        hostname: kafkamanager
        ports:
            - 9000:9000
        environment:
            - "ZK_HOSTS=zookeeper1:22181,zookeeper2:32181,zookeeper3:42181"
        depends_on:
            - kafka
        networks:
            - broker-net
    kowl:
        image: quay.io/cloudhut/kowl:master
        restart: unless-stopped
        hostname: kowl
        ports:
            - "8077:8077"
        volumes:
            - ./kowl-config.yaml:/etc/kowl/config.yaml
        entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
        networks:
            - broker-net
        depends_on:
            - kafka

# Networks to be created to facilitate communication between containers
networks:
    broker-net:
        name: broker-net
        external: true